name: C/C++ CI

on:
  push:
    branches: [ pqy-2021.05 ]
  pull_request:
    branches: [ pqy-2021.05 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: make hotspot_defconfig
    - name: make
      run: make -j2 > /dev/null
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
